// Generated by CoffeeScript 1.9.1
(function() {
  var cl, mssql;

  cl = console.log;

  mssql = require('mssql');

  mssql.connect('mssql://samUser:!@#User@152.99.147.11:1433/samcheok_2009').then(function() {
    return new mssql.Request().query('select count(*) from DUAL').then(function(recordset) {
      cl('recordset');
      cl(recordset);
      return mssql.close();
    })["catch"](function(err) {
      cl('err');
      cl(err.toString());
      return mssql.close();
    });
  })["catch"](function(err) {
    cl(err.toString());
    return mssql.close();
  });

}).call(this);
